#!/bin/sh
# kills all processes which have $* in its name
# $Id: killer,v 1.1 2001-06-13 13:55:24 jacorb Exp $
PIDS=`ps -xa | grep $* | awk '{print $1}'`
for pid in ${PIDS} 
do
	echo killing pid $pid
	kill -9 $pid
done

