/**
 * WARNING: THIS IS A COMPATIBILITY DUMMY NEEDED UNTIL SOMEONE FINDS
 * THE OFFICIAL IDL FILE
 *
 *  $Id: SendingContext.idl,v 1.1 2001-11-16 13:30:08 jacorb Exp $ */


#ifndef __SENDING_CONTEXT_IDL
#define __SENDING_CONTEXT_IDL

#pragma prefix "omg.org"

module SendingContext {
    interface RunTime{};
};

#endif
